<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Question;
use App\Models\Attribution;
use Attribute;

use function Ramsey\Uuid\v1;

class QuestionSeeder extends Seeder
{

  public function run(): void
  {
    dump('attribution');
    $attribution = [
      ['name' => 'Problemsolving'],
      ['name' => 'Resilience'],
      ['name' => 'Problemfocus'],
      ['name' => 'Timeperspective'],
      ['name' => 'Selfesteem'],
      ['name' => 'Selfunderstand'],
      ['name' => 'Communication'],
    ];
    Attribution::insert($attribution);


    dump('question');
    $question = [
      ['content' => '問題の解決方法を考えるとき，いくつもの方法を考える', 'attribution_id' => 1],
      ['content' => '困ったとき，状況について調べ，いろいろな情報を得る', 'attribution_id' => 1],
      ['content' => '問題に直面したとき，周囲の環境要因についても分析する', 'attribution_id' => 1],
      ['content' => '問題を解決した後，どこが上手く行ってどこが失敗だったかを分析してみる', 'attribution_id' => 1],
      ['content' => '決断をするとき，いくつかの選択肢を比較検討する', 'attribution_id' => 1],
      ['content' => '問題の解決に最初に失敗してしまうと解決できないと考えてしまう', 'attribution_id' => 1],
      ['content' => '問題解決のための時間を取らずにただボーッとしている', 'attribution_id' => 1],
      ['content' => '問題を解決しようとしても現実的に考えられず，右往左往する', 'attribution_id' => 1],
      ['content' => '緊張しすぎて問題を解決するいろいろな方法を考えることができない', 'attribution_id' => 1],
      ['content' => '問題に直面したとき，解決できる問題かどうか確信が持てない', 'attribution_id' => 1],
      ['content' => 'はじめは解決が困難に思える問題でもほとんどのことは解決できる', 'attribution_id' => 1],
      ['content' => '下した決断についてはその後も満足している', 'attribution_id' => 1],
      ['content' => '問題解決のための計画を立てるとき上手く行くと確信している', 'attribution_id' => 1],
      ['content' => '時間を掛けて努力すればほとんどの問題を解決できる', 'attribution_id' => 1],
      ['content' => '新しい状況で問題が生じても解決できる自信がある', 'attribution_id' => 1],
      ['content' => '色々なことに挑戦することが好きだ', 'attribution_id' => 2],
      ['content' => '珍しい体験や新しいことに魅力を感じる', 'attribution_id' => 2],
      ['content' => '物事に対する好奇心や関心が高い方だ', 'attribution_id' => 2],
      ['content' => '私は知識の幅を広げたいと強く思う', 'attribution_id' => 2],
      ['content' => '困難があっても、それは人生において意義深いものだと感じる', 'attribution_id' => 2],
      ['content' => '慣れていないことに取り組むのが苦手な方だ', 'attribution_id' => 2],
      ['content' => '新たなことに取り組むのは少し億劫だ', 'attribution_id' => 2],
      ['content' => '感情をコントロールすることに長けている', 'attribution_id' => 2],
      ['content' => '自分が動揺した時でも、自分を静めることができる', 'attribution_id' => 2],
      ['content' => 'いつも冷静な状態でいられるように意識している', 'attribution_id' => 2],
      ['content' => '途中で諦めずに最後まで頑張るねばり強い人間だ', 'attribution_id' => 2],
      ['content' => '気分転換するのが苦手で、なかなかリフレッシュできない', 'attribution_id' => 2],
      ['content' => 'つらい出来事が起こると、耐えることが難しくなる', 'attribution_id' => 2],
      ['content' => 'その日の気分に左右されて、行動パターンが変わってしまうことが多い', 'attribution_id' => 2],
      ['content' => 'あきっぽさを持っていて、物事に興味を持つ時間が短い', 'attribution_id' => 2],
      ['content' => '怒りを感じると、つい抑えられなくなってしまう傾向がある', 'attribution_id' => 2],
      ['content' => '未来は希望に満ちていて、素晴らしいことが起こると信じている', 'attribution_id' => 2],
      ['content' => '今後の展望を見ると、明るい道が待っていると思っている', 'attribution_id' => 2],
      ['content' => '自分の将来には希望を持っていて、良いことが待っていると思っている', 'attribution_id' => 2],
      ['content' => '自分には将来達成したい目標がある', 'attribution_id' => 2],
      ['content' => '自分の目標に向けて努力を積み重ねている', 'attribution_id' => 2],
      ['content' => '考えを整理して、状況を明確に把握できるようにした', 'attribution_id' => 3],
      ['content' => '望ましくない状況の要因を考慮し、解決方法を考えた', 'attribution_id' => 3],
      ['content' => '問題の背後にある原因を探り出すために努力した', 'attribution_id' => 3],
      ['content' => '状況を振り返りながら、その経緯を理解しようとした', 'attribution_id' => 3],
      ['content' => '状況を理解するために情報を収集したり調査したりした', 'attribution_id' => 3],
      ['content' => '行動計画を立てる前に問題の要素を分析し、優先順位を決めた', 'attribution_id' => 3],
      ['content' => '自分がやるべきことを考え出した', 'attribution_id' => 3],
      ['content' => '動するための計画を練った', 'attribution_id' => 3],
      ['content' => '問題に向き合って適切な対策を考案した', 'attribution_id' => 3],
      ['content' => '問題の本質を捉えて、どうやって解決できるかを考えた', 'attribution_id' => 3],
      ['content' => '解決への道筋を考慮して具体的なアイデアを出した', 'attribution_id' => 3],
      ['content' => '問題解決の結果に基づいて将来の展開を考慮した', 'attribution_id' => 3],
      ['content' => '自分の感情について考えながら行動することを意識した', 'attribution_id' => 3],
      ['content' => '自分のやりたいことを考えてみた', 'attribution_id' => 3],
      ['content' => '自分の将来について見通しを持とうと考えた', 'attribution_id' => 3],
      ['content' => '自分が将来どうなっていたいかを考えた', 'attribution_id' => 3],
      ['content' => 'その問題について、他の人の意見やアドバイスを聞いてみた', 'attribution_id' => 3],
      ['content' => 'ニュースや雑誌などを通じて、その問題に関する情報を入手した', 'attribution_id' => 3],
      ['content' => '問題の所在を明確にするために、様々な調査を行った', 'attribution_id' => 3],
      ['content' => 'その問題について他の人に相談した', 'attribution_id' => 3],
      ['content' => '共通の経験を持つ人に話を聞いてみて参考にした', 'attribution_id' => 3],
      ['content' => '将来の目標や計画をある程度描いている', 'attribution_id' => 4],
      ['content' => '自分の将来を考えて、現在から準備を進めている', 'attribution_id' => 4],
      ['content' => '将来達成したい目標を持っている', 'attribution_id' => 4],
      ['content' => '将来の方向性が明確に定まっていなくて、漠然としている', 'attribution_id' => 4],
      ['content' => '将来のことを思い描くことにあまり興味がない', 'attribution_id' => 4],
      ['content' => '将来に向けて期待感や希望を抱いている', 'attribution_id' => 4],
      ['content' => '10年後の自分の姿については、今のところ具体的なイメージが持てない', 'attribution_id' => 4],
      ['content' => '自分の将来は、自分の力で築いていけると信じている', 'attribution_id' => 4],
      ['content' => '自分の将来について不安や不確かさを感じている', 'attribution_id' => 4],
      ['content' => '毎日の生活が充実していて、満足している', 'attribution_id' => 4],
      ['content' => '今の生活には満足しており、幸せを感じている', 'attribution_id' => 4],
      ['content' => '毎日のルーティンが同じで、ワンパターンな感じで退屈している', 'attribution_id' => 4],
      ['content' => '毎日が何気なく過ぎていく感じがする', 'attribution_id' => 4],
      ['content' => '現在の自分が、本来の自分とは違うような気がしている', 'attribution_id' => 4],
      ['content' => '過去の自分を肯定し、受け入れることができる自信がある', 'attribution_id' => 4],
      ['content' => '過去の出来事を思い出すことが、あまり好きではない', 'attribution_id' => 4],
      ['content' => '過去の経験は苦しいものが多く、辛い思い出ばかりが残っている', 'attribution_id' => 4],
      ['content' => '過去の出来事について、なかなか忘れられずに引きずっている', 'attribution_id' => 4],
      ['content' => '自分ならではの個性を重要視している', 'attribution_id' => 5],
      ['content' => '自分には、自分だけの人生があると思っていて、それが良いと思っている', 'attribution_id' => 5],
      ['content' => '自分の良い面も悪い面も含めて、ありのままの自分を受け入れることができる', 'attribution_id' => 5],
      ['content' => '自分の個性に抵抗せず、むしろそれを受け入れている', 'attribution_id' => 5],
      ['content' => '自分の夢を叶えるために積極的に取り組み、情熱を注いでいる', 'attribution_id' => 5],
      ['content' => '自分が情熱を注いで取り組んでいることに充実感を感じている', 'attribution_id' => 5],
      ['content' => 'ポジティブな姿勢で物事に取り組むことで、成果を上げることができる', 'attribution_id' => 5],
      ['content' => '自分の良い面をより伸ばすように心掛けている', 'attribution_id' => 5],
      ['content' => 'やりたいことに情熱を注ぎ、やる気に満ちた生活を送っている', 'attribution_id' => 5],
      ['content' => '本当にやりたいことが何なのか分かっていない', 'attribution_id' => 5],
      ['content' => '自分には目標というものがなく、模索している', 'attribution_id' => 5],
      ['content' => '生活がとても楽しく、充実感を感じている', 'attribution_id' => 5],
      ['content' => 'わだかまりがなく、心地よくスッキリしている', 'attribution_id' => 5],
      ['content' => '自分の日々の活動や成果に満足感と充実感を感じている', 'attribution_id' => 5],
      ['content' => '精神的に穏やかで楽な気分を保っている', 'attribution_id' => 5],
      ['content' => '自分が好きなことに時間を使い、それを楽しんでいる', 'attribution_id' => 5],
      ['content' => '自分自身を束縛せず、自由に生きている', 'attribution_id' => 5],
      ['content' => '今の現状に満足感がもてない', 'attribution_id' => 5],
      ['content' => '心から楽しいと思える瞬間や体験がない', 'attribution_id' => 5],
      ['content' => '人間関係において一定の距離を保つことがあり、その距離がコミュニケーションの妨げをしているように感じている', 'attribution_id' => 5],
      ['content' => '自分の内面を他人に見せないようにしていることがあり、こころを閉ざしているように感じている', 'attribution_id' => 5],
      ['content' => '自分は孤立しているように感じる', 'attribution_id' => 5],
      ['content' => '他人を信用することに対してハードルを感じている', 'attribution_id' => 5],
      ['content' => '友人との関係性において、心理的な距離を感じてしまい、孤独感や悲しみを抱えてしまう', 'attribution_id' => 5],
      ['content' => '友人と話していても話が噛み合わず、わずらわしい', 'attribution_id' => 5],
      ['content' => '他人と好意的になろうと思わない', 'attribution_id' => 5],
      ['content' => '相手に気を配りながらも自分の言いたいことを言うことができる', 'attribution_id' => 5],
      ['content' => '自分の納得のいくまで相手と話し合うようにしている', 'attribution_id' => 5],
      ['content' => '疑問だと感じたらそれらを堂々と言える', 'attribution_id' => 5],
      ['content' => '友だちと真剣に話し合う', 'attribution_id' => 5],
      ['content' => '人前でもこだわりなく自由に感じたままを言うことができる', 'attribution_id' => 5],
      ['content' => '人前でもありのままの自分を出せる', 'attribution_id' => 5],
      ['content' => '自主的に友人に話しかけていく', 'attribution_id' => 5],
      ['content' => '人から何が言われないか、変な目で見られないかと気にしている', 'attribution_id' => 5],
      ['content' => '人に対して、自分のイメージを悪くしないかと恐れている自分が他人の目にどう映るかを意識すると身動きできなくなる', 'attribution_id' => 5],
      ['content' => '他人に自分の良いイメージだけを印象づけようとしている', 'attribution_id' => 5],
      ['content' => '無理して人に合わせようとしてきゅうくつな思いをしている', 'attribution_id' => 5],
      ['content' => '社交能力に自信がある', 'attribution_id' => 6],
      ['content' => '社交範囲が広い', 'attribution_id' => 6],
      ['content' => '同年代の異性と楽しく話ができる', 'attribution_id' => 6],
      ['content' => '異性の誘い方が上手い', 'attribution_id' => 6],
      ['content' => '人に対して思いやりがある', 'attribution_id' => 6],
      ['content' => '人に対して寛大である', 'attribution_id' => 6],
      ['content' => 'おおらかな人柄である', 'attribution_id' => 6],
      ['content' => '自分の生き方に自信がある', 'attribution_id' => 6],
      ['content' => '個性的な生き方をしている', 'attribution_id' => 6],
      ['content' => '自分に自信がある', 'attribution_id' => 6],
      ['content' => '几帳面な性格である', 'attribution_id' => 6],
      ['content' => '自分に厳しい', 'attribution_id' => 6],
      ['content' => '責任感が強い', 'attribution_id' => 6],
      ['content' => '体力・運動能力に自信がある', 'attribution_id' => 6],
      ['content' => '運動神経が発達している', 'attribution_id' => 6],
      ['content' => 'スポーツマンタイプに見られる', 'attribution_id' => 6],
      ['content' => '得意なスポーツがある', 'attribution_id' => 6],
      ['content' => '性的テクニックに自信がある', 'attribution_id' => 6],
      ['content' => '性的能力に自信がある', 'attribution_id' => 6],
      ['content' => '性的経験が豊富である', 'attribution_id' => 6],
      ['content' => '自由に使えるお金が多い', 'attribution_id' => 6],
      ['content' => '家庭が裕福である', 'attribution_id' => 6],
      ['content' => '経済的な面で自信がある', 'attribution_id' => 6],
      ['content' => '社会的に評判の良い大学に在籍していた or いる', 'attribution_id' => 6],
      ['content' => '出身校が有名である', 'attribution_id' => 6],
      ['content' => '家や大学などの社会的背景に自信がある', 'attribution_id' => 6],
      ['content' => '知的知能に自信がある', 'attribution_id' => 6],
      ['content' => '人より色々なことを知っている', 'attribution_id' => 6],
      ['content' => '頭の回転が速い', 'attribution_id' => 6],
      ['content' => '目鼻立ちが整っている', 'attribution_id' => 6],
      ['content' => '自分の外見に自信がある', 'attribution_id' => 6],
      ['content' => '自分の顔に気に入っているところがある', 'attribution_id' => 6],
      ['content' => '趣味・特技に自信がある', 'attribution_id' => 6],
      ['content' => '特技がある', 'attribution_id' => 6],
      ['content' => '自分の衝動や欲求を抑える', 'attribution_id' => 7],
      ['content' => '自分の感情をうまくコントロールする', 'attribution_id' => 7],
      ['content' => '善悪の判断に基づいて正しい行動を選択する', 'attribution_id' => 7],
      ['content' => '周りの期待に応じた振る舞いをする', 'attribution_id' => 7],
      ['content' => '自分の考えを言葉でうまく表現する', 'attribution_id' => 7],
      ['content' => '自分の気持ちをしぐさでうまく表現する', 'attribution_id' => 7],
      ['content' => '自分の気持ちを表情でうまく表現する', 'attribution_id' => 7],
      ['content' => '自分の感情や心理状態を正しく察してもらう', 'attribution_id' => 7],
      ['content' => '相手の考えを発言から正しく読み取る', 'attribution_id' => 7],
      ['content' => '相手の気持ちをしぐさから正しく読み取る', 'attribution_id' => 7],
      ['content' => '相手の気持ちを表情から正しく読み取る', 'attribution_id' => 7],
      ['content' => '相手の感情や心理状態を敏感に感じ取る', 'attribution_id' => 7],
      ['content' => '会話の主導権を握って話を進める', 'attribution_id' => 7],
      ['content' => 'まわりとは関係なく自分の意見や立場を明らかにする', 'attribution_id' => 7],
      ['content' => '納得させるために相手に柔軟に対応して話を進める', 'attribution_id' => 7],
      ['content' => '自分の主張を論理的に筋道を立てて説明する', 'attribution_id' => 7],
      ['content' => '相手の意見や立場に共感する', 'attribution_id' => 7],
      ['content' => '友好的な態度で相手に接する', 'attribution_id' => 7],
      ['content' => '相手の意見をできるかぎり受け入れる', 'attribution_id' => 7],
      ['content' => '相手の意見や立場を尊重する', 'attribution_id' => 7],
      ['content' => '人間関係を第一に考えて行動する', 'attribution_id' => 7],
      ['content' => '人間関係を良好な状態に維持するように心がける', 'attribution_id' => 7],
      ['content' => '意見の対立による不和に適切に対処する', 'attribution_id' => 7],
      ['content' => '感情的な対立による不和に適切に対処する', 'attribution_id' => 7],
    ];
    Question::insert($question);
  }
};
